version: '3'

services:
  jwtuserapi:
    image: app.jar
    ports:
      - "8070:8070"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3307/userdb",
        "spring.datasource.username" : "aziz",
        "spring.datasource.password" : "aziz",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: aziz
      MYSQL_PASSWORD: aziz
    ports:
      - "3307:3307"